### ISSUE TITLE
Games: fails to download and play PACMAN

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#101]
the spinner is on there forever, so maybe it doesnt init the emulator or doesnt recognize filetpye?
It used to work fine before...

**Comment by dnelband** [comment]
there were 2 different items with the same game, one of them wasnt working because the file didnt get uploaded, it was an old error that i didnt delete.
i've deleted the broken one,  here is the working version:
http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:2_1xHs57rsaNTX2HKjCyF3G3dphHp8h9FpF_2+type:game

**Comment by haschimoto** [comment]
please label anything done = green :)
