### ISSUE TITLE
Fruity Frank: Game doesnt load

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#115]
game paused but doesnt start/resume:
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp_11+type:game

**Comment by haschimoto** [comment]
game still doesnt work:
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp_11+type:game

I assume its again because of user = NULL?

**Comment by dnelband** [comment]
1 - the null was an error that i fixed, but it wasnt connected to your error
2 - the game loads & plays on fuckcf.cf - https://fuckcf.cf/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp_11+type:game, do you mean that the keyboard input doesnt work? thats because of really weird keyboard mapping, see my answer on issue #131

**Comment by haschimoto** [comment]
doesnt load and play under ff55 on windows here from fuckcf?

**Comment by haschimoto** [comment]
also not loading local... seems the file isnt downloaded at all?

**Comment by haschimoto** [comment]
it claims to have now downloaded the file in cache (69 peers), but still only shows this:
![snap 2017-10-21 at 14 54 37](https://user-images.githubusercontent.com/20817185/31851936-e4c57c88-b66f-11e7-99b7-4b3661c62b96.png)

**Comment by dnelband** [comment]
this is how i view it on chrome / firefox, fuckcf.cf doesnt load so i cant say, but its on mac so i need to test on windows, ill test it in a few hours when i'll get a windows pc to work on, i'll update. anyway, i tried to configure something with BFU, it might have affected this, now ive removed that code, so maybe try to update the site, but anyway ill test it on windows soon

![screen shot 2017-10-21 at 15 02 04](https://user-images.githubusercontent.com/5212537/31852038-20b4ae20-b671-11e7-93a9-aef8118df57a.png)
![screen shot 2017-10-21 at 15 09 05](https://user-images.githubusercontent.com/5212537/31852080-d172c4fe-b671-11e7-9700-e0f0bc6bec16.png)

![screen shot 2017-10-21 at 15 03 08](https://user-images.githubusercontent.com/5212537/31852040-20ed65e4-b671-11e7-8194-8240c4cee356.png)

**Comment by haschimoto** [comment]
STILL not working on Windows and FF.

**Comment by dnelband** [comment]
ok after testing on 2 windows peers with firefox, i know what the problem is:
1 - we used to load the game emulator scrips dynamically based on which file type the item is
2 - a zeronet update 3 months ago created a restriction and made it impossible to load a javascript file dynamically due to security issues
3 - we needed then to load all of the scripts all of the time to make everything work
3  this solution isnt optimal but due to the issues mentioned before its the only one that works normal, except on windows firefox, in which there is a JS error because of a conflict with another emulator library. 

the only solution is to create different html pages for each content viewer, but since this problem only occurs on windows firefox / cpc emulator, it seems an overkill. should i implement different html pages for every content viewer?

**Comment by haschimoto** [comment]
Works!
