### ISSUE TITLE
NES, Atari, etc.: Keyboard doesnt seem to work, cannot control game

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#131]
e.g.
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp_15+type:game

**Comment by dnelband** [comment]
1 - NES - the example you gave - super mario bros - works both on local & proxy, though the keyboard mapping is unusual, but you can see it when you click on "how to play" & it works
2 - CPC - the example you gave in another ticket - fruity frank - has really weird keyboard mapping: x - right , z - left, ö - up, . - down (on my mac keyboard). in any case thats also a problem because its really not obvious, solution - i'll create a table called "game-key-mapping" to attach to certain game items. i'll mark this ticket as "done" when im finished with that implementation

**Comment by dnelband** [comment]
actually looking at fruity frank, it shows the key mapping at the start screen
