### ISSUE TITLE
List Entries: Stop the animation re-sorting, display variable grid as it ends up shown right away

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#133]

**Comment by haschimoto** [comment]
@dnelband : please fix this next.

**Comment by dnelband** [comment]
Hi Clemens, im working on it but the api has no built in stop animation, so i need to do a work around. Im on it

**Comment by dnelband** [comment]
on first load it shows it without animated resorting, but when user re-sorts in any way it still moves, but less of course. is it ok or should i  make it without animation at all?

**Comment by dnelband** [comment]
it seems that the animation is really build in with this library, i'll try to find another one without animation

**Comment by dnelband** [comment]
i've managed to remove most of the animation at first load, but the initial visual sorting seems to be necessary for the masonry effect. i've tried a couple of other libraries but they all have this default animation. please check it now, is this ok? if not then we'll probably have to think about another solution other then the masonry look (which is a shame cause imo it looks good). i think now without the extra sorting it looks ok, but if not we can just make it an equal sized tile grid, though it wouldnt look as nice

**Comment by haschimoto** [comment]
it looks broken:
tiles heights seem not correct or sometimes "underlap" other tiles:
![snap 2017-10-21 at 14 21 21](https://user-images.githubusercontent.com/20817185/31851692-50f7e8b4-b66b-11e7-8f5d-47bbbae40ac5.png)

**Comment by dnelband** [comment]
this happens due to the fact that the images are loaded only after the DOM (html elements) are ready, so the masonry renders the height of the tiles without the full image loaded, which results in this error, 2 solutions:
1 - set a default height for the items img height - doesnt effect loading time & looks more or less normal
2 - post-loading, get the height of every image & set the item's height while hiding the items until it is calculated / resort once all the image heights 

obviously the first option is the better of the two, but the second one is also an option if its important for you to have the different sizes. ive implemented the first one, let me know if its ok
