### ISSUE TITLE
IFS 2.0: BFS: Show peers info even if not downloaded yet, as this seems possible (see ZeroUP)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#137]

**Comment by dnelband** [comment]
it is possible but this info is available only for big files, i.e only files above 10mb have the following fields: bytes_downloaded, download_percent, peer_leech, peer_seed, pieces,
pieces_downloaded. im implementing it,  but testing it will take a bit of time because it involves uploading / deleteing big files multiple times. i'll update
