### ISSUE TITLE
Says "Fetching piecemap information" even though it is a single file that has already been completely loaded (this needs to be done properly now, i hate jumping back and forth....)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#173]
![snap 2018-04-11 at 23 01 34](https://user-images.githubusercontent.com/20817185/38643122-6ac460b2-3ddc-11e8-8838-3b95392b12ff.png)

**Comment by dnelband** [comment]
there is a problem with determining weather a file is a bigFile (with pieces) or a single file, because up until the download start the piecemap information is not in the information object provided by ZeroNet. so there is another state, before any determinable information is recieved, there will be a loading spinner
