### ISSUE TITLE
games_viewer: allow comments and continue playing the game

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#53]

**Comment by haschimoto** [comment]
that is not fixed:
-  if one writes a comment, he needs to go back to the game and the game recapture focus by clicking on the game window
- in the comment filed, using ARROW keys is not working properly.

**Comment by dnelband** [comment]
ive tried several ways but it always ends up in needing to click on the game screen to continue. it also makes sense to "pause" the game while writing a comment, and return to it on click when ready. i can make an overlay with "pause" & "click here to continue" ?

in order to capture text and make the solution global (to work with all emulators) i needed to write a key-map to enable users to comment. now left & right arrows are working, but up & and down is tricky and i didnt find a solution for that yet.

**Comment by haschimoto** [comment]
Pause and continue is fine.
