### ISSUE TITLE
[viewer]: loading bigger videos when file not found stops after a relative short time and shows empty videoplayer

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#73]
in the past it was loading 200+MB videos for 10 minutes or longer before aborting "file not found"

**Comment by dnelband** [comment]
the only 200mb video i could reproduce this error until now is this one - http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:user+cl:15fDN4wasXuyS8krtKvrxEVmWWLz6Qh518+ch:3_1xHs57rsaNTX2HKjCyF3G3dphHp8h9FpF

and that was not loading due to name + format problem (now its fixed)
other then that other big videos seem to be loading fine.

**Comment by haschimoto** [comment]
what was the problem with that name if it was not BIG letters?
