### ISSUE TITLE
MY Channels: cannot use Cluster1 if I already use Cluster0 ?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#94]
i have 2 channels on Cluster0 and 1 on Cluster1.

- Uploading on Cluster0 WORKS, but uploading anything to Cluster1 Channel FAILS (upload takes forever, but the STATE never changes to indicate anything is uploading):
![snap 2017-04-30 at 10 43 43](https://cloud.githubusercontent.com/assets/20817185/25562948/0503e9a6-2d92-11e7-8f62-850c4be0ef34.png)

- creating a new channel on Cluster1 also FAILS, the create channel button if pressed doesnt do anything:
![snap 2017-04-30 at 10 49 42](https://cloud.githubusercontent.com/assets/20817185/25562990/c411453c-2d92-11e7-8c51-8f868fb8837f.png)

**Comment by haschimoto** [comment]
the ODD thing is:
i have 1 channel on Cluster0 and 1 on Cluster1.
Uploading on Cluster0 WORKS, but uploading anything to Cluster1 Channel FAILS

**Comment by haschimoto** [comment]
creating a new channel on Cluster1 also FAILS, the create channel button if pressed doesnt do anything:
![snap 2017-04-30 at 10 49 42](https://cloud.githubusercontent.com/assets/20817185/25562990/c411453c-2d92-11e7-8c51-8f868fb8837f.png)

**Comment by haschimoto** [comment]
whereas on Cluster 0, the CHANNEL WAS CREATED 3xtimes!!!!!!
![snap 2017-04-30 at 10 51 01](https://cloud.githubusercontent.com/assets/20817185/25563003/fd427d08-2d92-11e7-9c74-739d81c81c9e.png)

**Comment by haschimoto** [comment]
did a new ticket to seperate all the different issues

**Comment by haschimoto** [comment]
i suspect the internal routing is not working, like even if I select Cluster1 from the dropdown, somehow uploading or adding new stuff is blocked or doing an error, because it DOES NOT target Cluster1 or any channel on there correctly?

**Comment by haschimoto** [comment]
found out the data.json contains only NULL
![snap 2017-04-30 at 11 52 35](https://cloud.githubusercontent.com/assets/20817185/25563369/899d2df4-2d9b-11e7-8497-901af8cca4c2.png)

**Comment by haschimoto** [comment]
so when completely removing data.json and content.json and then press "Re-Publish" button in frontend creates those two files again, but data.json still containing NULL

**Comment by haschimoto** [comment]
update2:
I figured it out: the problem was that the created channel had the same 3_userstring entry as on Cluster0, which creates problems in the way we reference channels and content.
I manually updated the channel number and recreated a fresh one, but saw that on cluser0 the next channel_id was not counted up, possibly creating another conflict when creating another channel on Cluster0, which then would again have an identical 4_userstring on Cluster1 and Cluster0 in the same userdata/data.json file.

**Comment by dnelband** [comment]
you were unable to upload items / create new channels on cluster 1 because of the data.json file that had only "null" as content. the function to create a new channel / item didnt account for this case so it resulted in an error, sometimes it would create the item / channel in the other cluster regardless. now i've fixed it, upon creating a new channel in cluster 1 with that user the data.json file would be fixed and you could use it again

i didnt encouter this error before (i had to manually replace the content in my data.json with "null" to work on it), and i looked through all of the users data.json and it all seems standard, so i think this happend because you created a new channel when i sign & published something that created this error, before i signed & published the fix

try to create a new channel on cluster 1

**Comment by haschimoto** [comment]
works
