### ISSUE TITLE
UPLOAD: Uploading 1 file >50MB at some point times out and results in a video saying 0 PEERS and not in local cache

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#99]
the idea is to analyze the "upload process" and see to make it much faster, as it really only copies one local file to the local data/ifscluster folder location and adds the metadata to the json-files:
![snap 2017-05-19 at 22 54 01](https://cloud.githubusercontent.com/assets/20817185/26266565/2496ea80-3ce6-11e7-8892-6a5abab112d2.png)

**Comment by haschimoto** [comment]
the idea is to analyze the "upload process" and see to make it much faster, as it really only copies one local file to the local data/ifscluster folder location and adds the metadata to the json-files.

**Comment by dnelband** [comment]
i've tested it with this video:
http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1xHs57rsaNTX2HKjCyF3G3dphHp8h9FpF_22+type:video
at first it did like you said, and had 0 peers & not in cache. it was not added to the user's channel content.json because it had parenthesis in the name. now i've added parenthesis to the replace list on file name, and it works. 

does it work for you? or does your problem persist?
